# Generated by Django 6.0.2 on 2026-02-27 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
