# Generated by Django 6.0.2 on 2026-02-27 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_idempotency_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idempotency',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
