# Generated by Django 6.0.2 on 2026-02-27 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idempotency',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
